---

- hosts: 192.168.222.135
 
  tasks:
  - name: Installation du serveur Apache et PHP
    yum:
     name: "{{ item }}"
     state: present
    loop:
      -httpd
      - php

  - name: Arret du service nginx
    systemd:
     name: nginx
     state: stopped

  - name: Démarrage du serveur apache
    systemd:
     name: httpd
     state: started
